# Generated by Django 5.0.1 on 2025-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacysettings',
            name='show_connect_list',
            field=models.BooleanField(default=True),
        ),
    ]
