# Generated by Django 5.0.1 on 2025-11-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_privacysettings_show_connect_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacysettings',
            old_name='show_connect_list',
            new_name='show_connections',
        ),
    ]
