# Generated by Django 5.0.1 on 2025-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_show_connect_list_privacysettings_show_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_pic',
            field=models.ImageField(blank=True, default='defaults/default_cover.jpg', null=True, upload_to='cover_pics/'),
        ),
    ]
